import {Colors} from '../../../assets/colors';

const {StyleSheet} = require('react-native');

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
  },
  header: {
    backgroundColor: Colors.primaryColor,
    paddingVertical: '3.2%',
    alignItems: 'center',
    borderBottomLeftRadius: 25,
    borderBottomRightRadius: 25,
    marginBottom: 15,
  },
  headerText: {
    color: Colors.white,
    fontSize: 20,
    fontWeight: 'bold',
  },
  noteTitle: {
    color: Colors.black,
    fontSize: 15,
    fontWeight: 'bold',
  },
  noteContent: {
    color: 'rgba(0,0,0,0.5)',
    fontSize: 14,
    flexWrap: 'wrap',
  },
  noteItem: {
    paddingHorizontal: 12,
    paddingVertical: 12,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    shadowColor: Colors.primaryColor,
    elevation: 10,
    backgroundColor: Colors.white,
    borderRadius: 16,
    marginHorizontal: 20,
    marginVertical: 10,
  },
  noteIconView: {
    backgroundColor: Colors.primaryColor,
    borderRadius: 1000,
    paddingHorizontal: 13,
    paddingVertical: 13,
  },
  input: {
    borderWidth: 1,
    paddingHorizontal: 12,
    borderRadius: 8,
    borderColor: 'rgba(0,0,0,0.15)',
    paddingVertical: 8,
    color: Colors.black,
    fontSize: 14,
  },
  floatingButton: {
    position: 'absolute',
    alignSelf: 'flex-end',
    bottom: '5%',
    right: '10%',
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 8,
    backgroundColor: Colors.primaryColor,
    paddingHorizontal: '4%',
    paddingVertical: '3.5%',
    shadowColor: Colors.black,
    elevation: 8,
  },
  modal: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 20,
    backgroundColor: 'rgba(0,0,0,0.4)',
  },
  subModalView: {
    backgroundColor: Colors.white,
    width: '100%',
    borderRadius: 10,
    shadowColor: Colors.primaryColor,
    elevation: 15,
    paddingHorizontal: 20,
    paddingVertical: 15,
  },
  addNoteTitle: {
    color: Colors.primaryColor,
    fontSize: 24,
    alignSelf: 'center',
    fontWeight: 'bold',
  },
  buttonView: {
    backgroundColor: Colors.primaryColor,
    paddingVertical: 10,
    marginTop: 20,
    borderRadius: 8,
    alignItems: 'center',
  },
  buttonText: {
    color: Colors.white,
    fontSize: 14,
    fontWeight: 'bold',
  },
  closeIcon: {
    position: 'absolute',
    right: '5%',
    paddingHorizontal: 3,
    paddingVertical: 3,
    top: '5%',
  },
  delButTitle: {
    marginTop: 5,
    textAlign: 'center',
    fontSize: 18,
    color: 'rgba(0,0,0,0.6)',
  },
  emptyNoteText: {
    color: Colors.black,
    width: '85%',
    alignSelf: 'center',
    textAlign: 'center',
    fontSize: 20,
    fontWeight: '500',
  },
  divider: {
    height: 2,
    backgroundColor: 'rgba(0,0,0,0.15)',
    marginVertical: 8,
  },
});
